#!/bin/bash 
num1_1=1122 
num2_1=908 
 
num1_2=49608 
num2_2=33036 
 
and_1=$((num1_1 & num2_1)) 
or_1=$((num1_1 | num2_1)) 
xor_1=$((num1_1 ^ num2_1)) 
 
and_2=$((num1_2 & num2_2)) 
or_2=$((num1_2 | num2_2)) 
xor_2=$((num1_2 ^ num2_2)) 
 
echo "Для чисел $num1_1 и $num2_1:" 
echo "Побитовое И: $and_1" 
echo "Побитовое ИЛИ: $or_1" 
echo "Исключающее ИЛИ: $xor_1" 
 
echo "Для чисел $num1_2 и $num2_2:" 
echo "Побитовое И: $and_2" 
echo "Побитовое ИЛИ: $or_2" 
echo "Исключающее ИЛИ: $xor_2"
